import React, { Component } from 'react'
import WineIMG from "../../images/lucia-images/wine.jpg";

export default class Alcohol extends Component {
  render() {
    return (
      <div className="container-fluid">
        <div className="alc-container">
          <h1 className="max-auto text-center">Alcoholic Beverages</h1>
          <div className="center-image img-thumbnail">
            <img src={WineIMG} alt="WINE IMG" className="" />
          </div>
          <p className="left">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem fugit, excepturi animi officia sed molestias iure ipsam non eaque! Odit, obcaecati sequi in quidem voluptatibus laboriosam nostrum suscipit soluta dolor. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor architecto aperiam accusamus, quasi, esse officia sit, natus soluta ab impedit culpa nam nesciunt exercitationem necessitatibus.adipisicing elit. Exercitationem fugit, excepturi animi officia sed molestias iure ipsam non eaque! Odit, obcaecati sequi in quidem voluptatibus laboriosam nostrum suscipit soluta dolor. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor architecto aperiam accusamus, quasi, esse officia sit, natus soluta ab impedit culpa nam nesciunt exercitationem necessitatibus.adipisicing elit. Exercitationem fugit, excepturi animi officia sed molestias iure ipsam non eaque! Odit, obcaecati sequi in quidem voluptatibus laboriosam nostrum suscipit soluta dolor. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor architecto aperiam accusamus, quasi, esse officia sit, natus soluta ab impedit culpa nam nesciunt exercitationem necessitatibus.adipisicing elit. Exercitationem fugit, excepturi animi officia sed molestias iure ipsam non eaque! Odit, obcaecati sequi in quidem voluptatibus laboriosam nostrum suscipit soluta dolor. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor architecto aperiam accusamus, quasi, esse officia sit, natus soluta ab impedit culpa nam nesciunt exercitationem necessitatibus.adipisicing elit. Exercitationem fugit, excepturi animi officia sed molestias iure ipsam non eaque! Odit, obcaecati sequi in quidem voluptatibus laboriosam nostrum suscipit soluta dolor. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor architecto aperiam accusamus, quasi, esse officia sit, natus soluta ab impedit culpa nam nesciunt exercitationem necessitatibus.adipisicing elit. Exercitationem fugit, excepturi animi officia sed molestias iure ipsam non eaque! Odit, obcaecati sequi in quidem voluptatibus laboriosam nostrum suscipit soluta dolor. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor architecto aperiam accusamus, quasi, esse officia sit, natus soluta ab impedit culpa nam nesciunt exercitationem necessitatibus.</p>
          <p className="right">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem fugit, excepturi animi officia sed molestias iure ipsam non eaque! Odit, obcaecati sequi in quidem voluptatibus laboriosam nostrum suscipit soluta dolor. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem fugit, excepturi animi officia sed molestias iure ipsam non eaque! Odit, obcaecati sequi in quidem voluptatibus laboriosam nostrum suscipit soluta dolor. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor architecto aperiam accusamus, quasi, esse officia sit, natus soluta ab impedit culpa nam nesciunt exercitationem necessitatibus.adipisicing elit. Exercitationem fugit, excepturi animi officia sed molestias iure ipsam non eaque! Odit, obcaecati sequi in quidem voluptatibus laboriosam nostrum suscipit soluta dolor. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor architecto aperiam accusamus, quasi, esse officia sit, natus soluta ab impedit culpa nam nesciunt exercitationem necessitatibus.adipisicing elit. Exercitationem fugit, excepturi animi officia sed molestias iure ipsam non eaque! Odit, obcaecati sequi in quidem voluptatibus laboriosam nostrum suscipit soluta dolor. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor architecto aperiam accusamus, quasi, esse officia sit, natus soluta ab impedit culpa nam nesciunt exercitationem necessitatibus.adipisicing elit. Exercitationem fugit, excepturi animi officia sed molestias iure ipsam non eaque! Odit, obcaecati sequi in quidem voluptatibus laboriosam nostrum suscipit soluta dolor. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor architecto aperiam accusamus, quasi, esse officia sit, natus soluta ab impedit culpa nam nesciunt exercitationem necessitatibus.adipisicing elit. Exercitationem fugit, excepturi animi officia sed molestias iure ipsam non eaque! Odit, obcaecati sequi in quidem voluptatibus laboriosam nostrum suscipit soluta dolor. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor architecto aperiam accusamus, quasi, esse officia sit, natus soluta ab impedit culpa nam nesciunt exercitationem necessitatibus.adipisicing elit. Exercitationem fugit, excepturi animi officia sed molestias iure ipsam non eaque! Odit, obcaecati sequi in quidem voluptatibus laboriosam nostrum suscipit soluta dolor. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor architecto aperiam accusamus, quasi, esse officia sit, natus soluta ab impedit culpa nam nesciunt exercitationem necessitatibus.</p>

        </div>

      </div>

    )
  }
}
